name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: 
      run: |
        ssh -o StrictHostKeyChecking=no user@your_server_ip << 'EOF'
        cd /path/to/your/app
        git pull origin main
        npm install --production
        pm2 restart my-backend
        EOF
